services:
  klicme:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: klicme_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/production.db
    volumes:
      - ./data:/app/data
      - ./public/images/uploads:/app/public/images/uploads
    networks:
      - klicme_network
    # Запускаем миграцию БД и seed перед запуском сервера
    command: sh -c "node node_modules/.bin/prisma db push --skip-generate && node prisma/seed.js && node server.js"

networks:
  klicme_network:
    driver: bridge
